// <auto-generated />
using System;
using DashboardAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DashboardAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250402073304_CityInfoes")]
    partial class CityInfoes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DashboardAPI.Models.USR.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.ToTable("Users", "USR");
                });

            modelBuilder.Entity("DashboardAPI.Models.WTH.CityInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CityId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Capital")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Capital");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("City");

                    b.Property<string>("CityAscii")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CityAscii");

                    b.Property<string>("CityFarsiName")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CityFarsiName");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Country");

                    b.Property<string>("CountryFarsiName")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CountryFarsiName");

                    b.Property<string>("ISO2")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("ISO2");

                    b.Property<string>("ISO3")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("ISO3");

                    b.Property<double>("Lat")
                        .HasColumnType("float")
                        .HasColumnName("Latitude");

                    b.Property<double>("Lng")
                        .HasColumnType("float")
                        .HasColumnName("Longitude");

                    b.Property<string>("ProvinceFarsiName")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ProvinceFarsiName");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ProvinceName");

                    b.HasKey("Id");

                    b.ToTable("CityInfo", "WTH");
                });
#pragma warning restore 612, 618
        }
    }
}
